[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Netlify will use this Node version for builds/functions.
  NODE_VERSION = "20"
