[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/templates/**"]

[[redirects]]
  from = "http://x-ampledevelopment.co.uk/*"
  to = "https://x-ampledevelopment.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.x-ampledevelopment.co.uk/*"
  to = "https://x-ampledevelopment.co.uk/:splat"
  status = 301
  force = true

