// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzcezcoivezflchsewhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Y2V6Y29pdmV6ZmxjaHNld2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjY5ODcsImV4cCI6MjA2NDUwMjk4N30.qBhCFOChgP5i_Ymr_Gazdhd_jm6xyYhq3r0ZAkxwKJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);